### ISSUE TITLE
Demo is broken

### ISSUE THREAD

**Issue by MindFreeze** [picturae/openseadragonrgb#1]
The crossOriginPolicy on the source does not work anymore, so the demo for RGB is broken
```
openseadragonrgb.js:1 Uncaught SecurityError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.
```

**Comment by Pin0** [comment]
Thanks for catching this! Took a quick look but we do provide crossOriginPolicy: "Anonymous" to the OpenSeadragon viewer, this leads me to think it is a bug in Openseadragon itself. Have to investigate further but in the mean time you are welcome to suggest any fixes or ideas.

**Comment by Pin0** [comment]
The was some CORS issue with the deepzoom image we linked to (https://openseadragon.github.io/example-images/highsmith/highsmith.dzi) weird because it was not an issue before. Something is changed somewhere. Either in the headers of the dzi or in osd. I updated the example to use a local dzi which works.

For now I'm closing this issue.
